name: metrix_pilot
description: MetrixPilot guides teams through data complexity with an intuitive app that clearly visualizes metrics and KPIs. This solution seamlessly integrates with existing project management tools and turns complex data into actionable insights.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: 3.24.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #  fl_chart: ^0.68.0
  fl_chart:
    git:
      url: https://github.com/meltzow/fl_chart.git
      ref: main # You can specify a branch, tag, or commit hash here
  get: ^4.6.6
  flutter_launcher_icons: ^0.13.1
  atlassian_apis: ^0.15.0
  envied: ^0.5.4+1
  url_launcher: ^6.3.0
  yaml: ^3.1.0
  url_strategy: ^0.3.0
  drift: ^2.20.0
  drift_flutter: ^0.2.0
  riverpod: ^2.3.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.12
  #  devtools_extensions: ^0.2.2
  http_mock_adapter: ^0.6.1
  flutter_oss_licenses: ^3.0.2
  envied_generator: ^0.5.4+1
  json_serializable: ^6.8.0
  drift_dev: ^2.20.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    #    - images/a_dot_burr.jpeg
    - assets/images/
    - pubspec.yaml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

targets:
  $default:
    builders:
      drift_dev:
        options:
          fatal_warnings: true

#flutter_scripts
# see https://pub.dev/documentation/flutter_scripts/latest/
scripts:
  generate_files: flutter pub run build_runner build --delete-conflicting-outputs
  generate_icons: flutter pub run flutter_launcher_icons:main
  generate_screenshots_android: screenshots --config=screenshots.yaml
  generate_screenshots_ios: screenshots --config=screenshots-ios.yaml
  generate_licenses: flutter pub run flutter_oss_licenses:generate.dart